### ISSUE TITLE
Multiline code needs to be wrapped manually before quickview

### ISSUE THREAD

**Issue by danlooo** [fkeck/quickview#3]
Hello,

thank you very much for this useful Addin!

I have multiple statements separated by line breaks:

```
a <- 1
b <- 2
a + b
```

Quickview returns this error after selecting these 3 lines above:

```
Error in parse(text = comm) : <text>:2:1: unexpected symbol
1: View(a <- 1
2: b
   ^
```

The parsing error can be more or less reproduced with the function `View` and fixed by wrapping the statements using curly brackets:

```
packageVersion("quickview")
#> [1] ‘0.1.0’

a <- 1
b <- 2
a + b
#> 3

# works not
View(
    a <- 1
    b <- 2
    a + b 
)
#> Error during wrapup: unexpected ')' in ")"
#> Error: no more error handlers available (recursive errors?); invoking 'abort' restart

# works
View(
  {
    a <- 1
    b <- 2
    a + b  
  }
)
```
Indeed, these lines works with quick view as well:

```
{
a <- 1
b <- 2
a + b
}
```
I suggest adding curly brackets around every input code passed to quickview automatically. Doing so, we will have the same behavior as with RStudio ctrl+Enter to print the table in the console. This would be very helpful for quick-viewing multi line code like this:

``` 
x <- 5
iris |> dplyr::mutate(Sepal.x = Sepal.Width + x)
```

**Comment by fkeck** [comment]
Hello Daniel,
Thanks a lot for your very clear and complete feedback!
The fix you suggested works perfectly well and is now implemented.
100fb296d7b6ec1f825f68bcbd14c2d77e249739
